# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-09-30 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20150930_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='book_description',
            field=models.CharField(default='hello', max_length=700),
        ),
        migrations.AddField(
            model_name='article',
            name='book_image',
            field=models.CharField(default='book_title', max_length=10),
        ),
    ]
