# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-09-30 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20150930_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='book_description',
            field=models.CharField(default='(give description...)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='book_image',
            field=models.CharField(default='(book_title.jpg)', max_length=50),
        ),
    ]
