# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-10-02 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20150930_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(verbose_name='Publication Date'),
        ),
    ]
