# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-10-02 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20151003_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazine_title', models.CharField(max_length=100)),
                ('magazine_image', models.CharField(max_length=100)),
            ],
        ),
    ]
